[project]
name = "tapo-vision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "google-genai>=1.73.1",
    "imageio[ffmpeg]>=2.37.3",
    "ollama>=0.6.1",
    "openai>=2.32.0",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "rumps>=0.4.0",
    "ultralytics>=8.4.39",
]
